import { Market } from "./types";

export const mockMarkets: Market[] = [
  {
    id: 1,
    repo: "facebook/react",
    prNumber: 28453,
    title: "feat: Add concurrent rendering optimizations",
    author: "gaearon",
    probability: 92,
    price: 0.045,
    change: 47,
    volume: 12500,
    status: "open",
    tags: ["React", "Performance", "Core"],
    timeLeft: "2d 14h",
    participants: 234
  },
  {
    id: 2,
    repo: "vitejs/vite",
    prNumber: 15892,
    title: "fix: Resolve HMR issues with dynamic imports",
    author: "patak-dev",
    probability: 87,
    price: 0.032,
    change: 32,
    volume: 8900,
    status: "open",
    tags: ["Vite", "Bug Fix", "HMR"],
    timeLeft: "1d 8h",
    participants: 156
  },
  {
    id: 3,
    repo: "microsoft/TypeScript",
    prNumber: 56234,
    title: "feat: Improve type inference for mapped types",
    author: "RyanCavanaugh",
    probability: 94,
    price: 0.058,
    change: 28,
    volume: 15200,
    status: "review",
    tags: ["TypeScript", "Types", "Enhancement"],
    timeLeft: "3d 2h",
    participants: 312
  },
  {
    id: 4,
    repo: "vercel/next.js",
    prNumber: 67891,
    title: "feat: Add App Router streaming improvements",
    author: "timneutkens",
    probability: 89,
    price: 0.042,
    change: 18,
    volume: 9800,
    status: "open",
    tags: ["Next.js", "App Router", "Streaming"],
    timeLeft: "4d 12h",
    participants: 198
  },
  {
    id: 5,
    repo: "tailwindcss/tailwindcss",
    prNumber: 12345,
    title: "feat: Add new color palette and utilities",
    author: "adamwathan",
    probability: 85,
    price: 0.038,
    change: 22,
    volume: 7600,
    status: "review",
    tags: ["CSS", "Design", "Utilities"],
    timeLeft: "5d 18h",
    participants: 142
  },
  {
    id: 6,
    repo: "nestjs/nest",
    prNumber: 98765,
    title: "fix: Resolve dependency injection circular references",
    author: "kamilmysliwiec",
    probability: 91,
    price: 0.029,
    change: 35,
    volume: 5400,
    status: "open",
    tags: ["NestJS", "Bug Fix", "DI"],
    timeLeft: "1d 22h",
    participants: 89
  }
];